# Generated by Django 6.0 on 2025-12-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=55)),
                ('model', models.CharField(max_length=55)),
                ('year', models.IntegerField()),
                ('price', models.CharField(max_length=100)),
            ],
        ),
    ]
